### ISSUE TITLE
Why apply 'api' middleware?

### ISSUE THREAD

**Issue by wrabit** [thebachtiarz/laralock#1]
I thought all routes in routes/api.php already had api middleware applied?

https://github.com/thebachtiarz/laralock/blob/4539a47f7dd3a6968dcf7632bf2e088863d6d817/routes/api.php#L20

**Comment by thebachtiarz** [comment]
Thank you for the warning, and yes it was my mistake, because actually I want to create a middleware which only accepts from trusted front-end, but for now I haven't found the best way to create it.
